on:
  push:
    branches:
    - main
    
jobs:
  BuildISO:
    name: BuildISO
    runs-on: ubuntu-18.04
    steps:
    
      - run: git clone https://gitlab.archlinux.org/archlinux/archiso.git ~/archiso

      - run: git clone https://github.com/logzinga/elnathco.git 
  
      - run: cp -r elnathco/isoprofile ~/iso

      - run: sudo ~/archiso/archiso/mkarchiso -v -w /tmp -o ~/out ~/iso/isoprofile

      
    
